name: Trigger Vercel build after PR merge

on:
  pull_request:
    types: [closed]

jobs:
  trigger:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.Nova-TOKEN }}

      - name: Configure Git user
        run: |
          git config user.name "novagestionsoftware"
          git config user.email "novagestionsoftware@gmail.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "Trigger Vercel build by novagestionsoftware"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}
